/*
Copyright (C) 2020  Alessandro Giaquinto agiaquinto87@gmail.com
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
package jwalletGUI;

import JAddressBook.AddressEntry;
import JWalletGUIUtil.Messenger;
import JWalletSQL.JWalletDBLite;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alessandrogiaquinto
 */
public class MainWallet extends javax.swing.JFrame {

    /**
     * Creates new form MainWallet
     */
    public MainWallet() {
        initComponents();
        this.infoCenter = new Messenger(this.messageLabel);
        if (JWalletDBLite.makeReady()) {
            System.err.println("DB OK");
        } else {
            System.err.println("DB ERROR");
        } 
    }
    
    public static void initDB() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelRecap = new javax.swing.JPanel();
        panelIncome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIncome = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nameText = new javax.swing.JTextField();
        valueText = new javax.swing.JTextField();
        insertIncomeButton = new javax.swing.JButton();
        typeTabbedPane = new javax.swing.JTabbedPane();
        occasionalPanel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        weeklyPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        monthlyPanel = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yearlyPanel = new javax.swing.JPanel();
        descriptionText = new javax.swing.JTextField();
        AddressPanel = new javax.swing.JPanel();
        fromTextField = new javax.swing.JTextField();
        telephoneTextField = new javax.swing.JTextField();
        mailTextField = new javax.swing.JTextField();
        pullAddressButton = new javax.swing.JButton();
        pushAddressButton = new javax.swing.JButton();
        panelOutcome = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAddress = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        userAddress = new javax.swing.JTextField();
        telAddress = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        emailAddress = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labelSalut = new javax.swing.JLabel();
        labelDateTime = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(13, 40));

        javax.swing.GroupLayout panelRecapLayout = new javax.swing.GroupLayout(panelRecap);
        panelRecap.setLayout(panelRecapLayout);
        panelRecapLayout.setHorizontalGroup(
            panelRecapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
        );
        panelRecapLayout.setVerticalGroup(
            panelRecapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Riepilogo", panelRecap);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabella entrate"));
        jScrollPane1.setToolTipText("Elenco di tutte le entrate registrate e inserite in questa sessione");

        tableIncome.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        tableIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo entrata", "Nome", "Valore", "Attributo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableIncome.setToolTipText("Tabella di visualizzazione per tutte le entrate, sia fisse che variabili");
        jScrollPane1.setViewportView(tableIncome);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserimento"));

        nameText.setBackground(new java.awt.Color(230, 228, 230));
        nameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameText.setToolTipText("Inserire qui il nome dell'entrata fissa");
        nameText.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        valueText.setBackground(new java.awt.Color(230, 228, 230));
        valueText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valueText.setToolTipText("<html>\n<p>Inserire qui il valore della nuova entrata fissa</p></br>\n<p>E' possibile indicare i centesimi con il punto o con la virgola\n</html>");
        valueText.setBorder(javax.swing.BorderFactory.createTitledBorder("Valore in €"));
        valueText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueTextActionPerformed(evt);
            }
        });

        insertIncomeButton.setText("Inserisci nuova entrata");
        insertIncomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertIncomeButtonActionPerformed(evt);
            }
        });

        typeTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Occorrenza"));
        typeTabbedPane.setToolTipText("Occorrenza della prestazione");

        jCheckBox1.setText("Fatturabile?");
        jCheckBox1.setToolTipText("E' stata emessa fattura?");

        javax.swing.GroupLayout occasionalPanelLayout = new javax.swing.GroupLayout(occasionalPanel);
        occasionalPanel.setLayout(occasionalPanelLayout);
        occasionalPanelLayout.setHorizontalGroup(
            occasionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, occasionalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );
        occasionalPanelLayout.setVerticalGroup(
            occasionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(occasionalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        typeTabbedPane.addTab("Occasionale", occasionalPanel);

        jComboBox1.setMaximumRowCount(7);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato", "Domenica" }));
        jComboBox1.setToolTipText("Selezionare un giorno della settimana");

        jLabel4.setText("Si ripete ogni");

        javax.swing.GroupLayout weeklyPanelLayout = new javax.swing.GroupLayout(weeklyPanel);
        weeklyPanel.setLayout(weeklyPanelLayout);
        weeklyPanelLayout.setHorizontalGroup(
            weeklyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weeklyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        weeklyPanelLayout.setVerticalGroup(
            weeklyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weeklyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(weeklyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        typeTabbedPane.addTab("Settimanale", weeklyPanel);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 28, 1));
        jSpinner1.setToolTipText("Sono ammessi tutti i giorni dal 1 al 28 (inclusi)");

        jLabel2.setText("Si ripete ogni ");

        jLabel3.setText("giorno del mese");

        javax.swing.GroupLayout monthlyPanelLayout = new javax.swing.GroupLayout(monthlyPanel);
        monthlyPanel.setLayout(monthlyPanelLayout);
        monthlyPanelLayout.setHorizontalGroup(
            monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthlyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        monthlyPanelLayout.setVerticalGroup(
            monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthlyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        typeTabbedPane.addTab("Mensile", monthlyPanel);

        javax.swing.GroupLayout yearlyPanelLayout = new javax.swing.GroupLayout(yearlyPanel);
        yearlyPanel.setLayout(yearlyPanelLayout);
        yearlyPanelLayout.setHorizontalGroup(
            yearlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        yearlyPanelLayout.setVerticalGroup(
            yearlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        typeTabbedPane.addTab("Annuale", yearlyPanel);

        descriptionText.setBackground(new java.awt.Color(230, 228, 230));
        descriptionText.setToolTipText("E' consigliato aggiungere una motivazione");
        descriptionText.setBorder(javax.swing.BorderFactory.createTitledBorder("Motivazione"));

        AddressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Rubrica"));

        fromTextField.setBackground(new java.awt.Color(230, 228, 230));
        fromTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fromTextField.setToolTipText("Generalità del cliente");
        fromTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Da"));

        telephoneTextField.setBackground(new java.awt.Color(230, 228, 230));
        telephoneTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telephoneTextField.setToolTipText("Numero di telefono del cliente");
        telephoneTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Recapito"));

        mailTextField.setBackground(new java.awt.Color(230, 228, 230));
        mailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mailTextField.setToolTipText("Mail del cliente");
        mailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Mail"));

        pullAddressButton.setText("Importa");

        pushAddressButton.setText("Inserisci");

        javax.swing.GroupLayout AddressPanelLayout = new javax.swing.GroupLayout(AddressPanel);
        AddressPanel.setLayout(AddressPanelLayout);
        AddressPanelLayout.setHorizontalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fromTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telephoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pushAddressButton, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(pullAddressButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AddressPanelLayout.setVerticalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pullAddressButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pushAddressButton)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(typeTabbedPane, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(descriptionText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valueText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(AddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(insertIncomeButton))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertIncomeButton))
        );

        javax.swing.GroupLayout panelIncomeLayout = new javax.swing.GroupLayout(panelIncome);
        panelIncome.setLayout(panelIncomeLayout);
        panelIncomeLayout.setHorizontalGroup(
            panelIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIncomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelIncomeLayout.setVerticalGroup(
            panelIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIncomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelIncomeLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Entrate", panelIncome);

        javax.swing.GroupLayout panelOutcomeLayout = new javax.swing.GroupLayout(panelOutcome);
        panelOutcome.setLayout(panelOutcomeLayout);
        panelOutcomeLayout.setHorizontalGroup(
            panelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
        );
        panelOutcomeLayout.setVerticalGroup(
            panelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Uscite", panelOutcome);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rubrica"));

        tableAddress.setAutoCreateRowSorter(true);
        tableAddress.setBackground(new java.awt.Color(230, 228, 230));
        tableAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Rubrica"));
        tableAddress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Utente", "Telefono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableAddress.setToolTipText("La tua rubrica");
        tableAddress.setGridColor(new java.awt.Color(204, 204, 204));
        tableAddress.setPreferredSize(new java.awt.Dimension(225, 0));
        tableAddress.setShowGrid(true);
        jScrollPane2.setViewportView(tableAddress);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Ricerca"));

        jTextField1.setBackground(new java.awt.Color(230, 228, 230));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cerca per nome"));

        jButton1.setText("Ricerca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(230, 228, 230));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cerca per numero"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("oppure");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(24, 24, 24)
                .addComponent(jButton1))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Inserisci nuovo"));

        userAddress.setBackground(new java.awt.Color(230, 228, 230));
        userAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        userAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Utente"));

        telAddress.setBackground(new java.awt.Color(230, 228, 230));
        telAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        telAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero"));

        jButton2.setText("Inserisci");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        emailAddress.setBackground(new java.awt.Color(230, 228, 230));
        emailAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        emailAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("E-mail"));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userAddress)
                    .addComponent(emailAddress)
                    .addComponent(telAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Rubrica", jPanel6);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelSalut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSalut.setText(" Benvenuto in JWallet!");
        labelSalut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        labelDateTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDateTime.setText("DateTime ");

        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText(" ");
        messageLabel.setToolTipText("Qui vengono visualizzate tutte le info");
        messageLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSalut, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(messageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelSalut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(messageLabel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void valueTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueTextActionPerformed

    private void insertIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertIncomeButtonActionPerformed
        String name = "", description = "";
        double value = 0.0;
        
        if (this.nameText.getText().isEmpty() || this.nameText.getText().isBlank()) {
            JOptionPane.showMessageDialog(panelIncome, "E' richiesto l'inserimento del nome", "Errore", JOptionPane.ERROR_MESSAGE);
            this.infoCenter.setErrorMessage("E' richiesto l'inserimento del nome");
            return;
        } else {
            name = this.nameText.getText();
            System.out.println(name);
        } 
            
        if (this.valueText.getText().isEmpty() || this.valueText.getText().isBlank()) {
            JOptionPane.showMessageDialog(panelIncome, "E' richiesto l'inserimento del valore", "Errore", JOptionPane.ERROR_MESSAGE);
            this.infoCenter.setErrorMessage("E' richiesto l'inserimento del valore");
            return;
        } else {
            this.valueText.setText(this.valueText.getText().replace(",", ".").replace("€", "").replace("$", ""));
            try {
                value = Double.parseDouble(this.valueText.getText()); 
            } catch(NumberFormatException ne) {
                JOptionPane.showMessageDialog(panelIncome, "Il valore inserito non è corretto", "Errore", JOptionPane.ERROR_MESSAGE);
                this.infoCenter.setErrorMessage("E' stato inserito un valore non numerico");
                this.flushFixedData();
                return;
            }
            
            System.out.println(value);
        }
        
        if (this.descriptionText.getText().isEmpty() || this.descriptionText.getText().isBlank()) {
            JOptionPane.showMessageDialog(panelIncome, "E' richiesto l'inserimento della motivazione", "Errore", JOptionPane.ERROR_MESSAGE);
            this.infoCenter.setErrorMessage("E' richiesto l'inserimento della motivazione");
            return;
        } else {
            description = this.descriptionText.getText();
            
            System.out.println(description);
        }
        
        switch (this.typeTabbedPane.getSelectedIndex()) {
            default -> {
                System.err.println("Occasionale");
            }
            case 1 -> {
                System.err.println("Settimanale");
            }
            case 2 -> {
                System.err.println("Mensile");
            }
            case 3 -> {
                System.err.println("Annuale");
            }
        }
        
        
        //String t = this.timeFixedComboBok.getSelectedItem();
        
        //FixedIncome t = new FixedIncome(name,value)
        
        //System.err.println(t.toString());
        
        // TODO Insert into array 
        // save into database
        DefaultTableModel table = (DefaultTableModel)this.tableIncome.getModel();
        table.addRow(new String[]{this.typeTabbedPane.getTitleAt(this.typeTabbedPane.getSelectedIndex()), name, "+ " + value});
        
        this.infoCenter.setPositiveMessage("Nuova entrata variabile inserita, +" + value + "€");
        
        this.flushFixedData();
    }//GEN-LAST:event_insertIncomeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String user, tel, email;
        
        try {
            user = this.userAddress.getText();
        } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(panelIncome, "Non è possibile tralasciare il campo Utente", "ERRORE", JOptionPane.ERROR_MESSAGE);
            this.infoCenter.setErrorMessage("Non è possibile tralasciare il campo Utente");
            return;
        }
        
        try {
            tel = this.telAddress.getText();
        } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(panelIncome, "Non è possibile tralasciare il campo Numero", "ERRORE", JOptionPane.ERROR_MESSAGE);
            this.infoCenter.setErrorMessage("Non è possibile tralasciare il campo Numero");
            return;
        }
        
        try {
            email = this.emailAddress.getText();
        } catch (NullPointerException ne) {
            JOptionPane.showMessageDialog(panelIncome, "Non è possibile tralasciare il campo Email", "ERRORE", JOptionPane.ERROR_MESSAGE);
            this.infoCenter.setErrorMessage("Non è possibile tralasciare il campo Email");
            return;
        }
        
        AddressEntry newEntry = new AddressEntry(user,tel,email); 
        
        DefaultTableModel table = (DefaultTableModel)this.tableAddress.getModel();
        table.addRow(new Object[]{user,tel,email});
        
        this.infoCenter.setMsg("Il record è stato inserito correttamente in rubrica");
        
        if (JWalletDBLite.insertAddress(user, tel, email)) {
            this.infoCenter.setPositiveMessage("La nuova entry " + user + " è stata inserita nel database");
        } else {
            this.infoCenter.setErrorMessage("Errore nell'inserimento del database");
        }
        
        System.err.println(newEntry.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWallet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressPanel;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JButton insertIncomeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelDateTime;
    private javax.swing.JLabel labelSalut;
    private javax.swing.JTextField mailTextField;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel monthlyPanel;
    private javax.swing.JTextField nameText;
    private javax.swing.JPanel occasionalPanel;
    private javax.swing.JPanel panelIncome;
    private javax.swing.JPanel panelOutcome;
    private javax.swing.JPanel panelRecap;
    private javax.swing.JButton pullAddressButton;
    private javax.swing.JButton pushAddressButton;
    private javax.swing.JTable tableAddress;
    private javax.swing.JTable tableIncome;
    private javax.swing.JTextField telAddress;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JTabbedPane typeTabbedPane;
    private javax.swing.JTextField userAddress;
    private javax.swing.JTextField valueText;
    private javax.swing.JPanel weeklyPanel;
    private javax.swing.JPanel yearlyPanel;
    // End of variables declaration//GEN-END:variables
    private Messenger infoCenter;
    
    private void flushVariableData() {
        this.nameText.setText("");
        this.valueText.setText("");
        this.descriptionText.setText("");
    }
    
    private void flushFixedData() {
        this.nameText.setText("");
        this.valueText.setText("");
        //this.timeFixedComboBok.setSelectedIndex(0);
    }
}
